datasources:
  - datasource:
      name: mysql
      url: jdbc:mysql://localhost:3306/employees
      username: root
      password: root

actions:
  - action:
      name: log
      type: log

queries:
  - query:
      name: get_30_eldest_employees
      query: |
        select *
        from employees
        order by birth_date
        limit 30;
      frequency:
        minutes: 15
      action: log
