datasources:
  - name: mysql
    url: jdbc:mysql://localhost:3306/employees
    username: root
    password: root

actions:
  - name: log
    type: LOG

queries:
  - name: get_30_eldest_employees
    source: mysql
    query: |
      select *
      from employees
      order by birth_date
      limit 30;
    frequency:
      seconds: 10
    action: log
