datasources:
  - name: mysql
    url: jdbc:mysql://localhost:3306/employees
    username: root
    password: root

actions:
  - name: log
    type: LOG
    folderBasePath: C:/Users/nicho_000/Documents/sql-scriptrunner/

queries:
  - name: get_30_eldest_employees
    source: mysql
    query: |
      select *
      from employees
      order by birth_date
      limit 30;
    frequency:
      seconds: 10
    action: log
  - name: get_20_youngest_employees
    source: mysql
    query: |
      select *
      from employees
      order by hire_date desc
      limit 20;
    frequency:
      seconds: 15
    action: log